apiVersion: v1
kind: Secret
metadata:
  name: smartbiz-secrets
type: Opaque
stringData:
  # En producción, usa un gestor de secretos real (AWS Secrets Manager / Vault)
  DATABASE_URL: "postgresql://admin:password123@smartbiz-db-service:5432/smartbiz_db?schema=public"
  JWT_SECRET: "TuSecretoSuperSeguroEnK8s"