-- AlterTable
ALTER TABLE "Company" ADD COLUMN     "currentCycleStart" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "invoiceCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "planStatus" TEXT NOT NULL DEFAULT 'ACTIVE',
ADD COLUMN     "planType" TEXT NOT NULL DEFAULT 'FREE';
